name: 'Tauri Plugin README Generator'
description: 'Generate README for Tauri Plugin Workspace'
branding:
  icon: 'code'
  color: 'green'
inputs:
  filename:
    description: 'Output filename'
    required: true
    default: 'README.md'
  folder:
    description: 'Path to location of plugins'
    required: true
    default: 'plugins'
  github_token:
    description: 'Use the variable secrets.GITHUB_TOKEN as value'
    required: true
runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - run: node dist/index.js
      shell: bash
      env:
        filename: ${{ inputs.filename }}
        folder: ${{ inputs.folder }}
        github_token: ${{ inputs.github_token }}
    - name: Update resources
      uses: test-room-7/action-update-file@v1
      with:
        file-path: ${{ inputs.filename }}
        commit-msg: Updated ${{ inputs.filename }}
        github-token: ${{ inputs.github_token }}
